namespace Canon.Emit

open System
open System.Text
open Canon.Core

module FsCheckEmitter =

    let rec extractGenerators (lattice: Lattice<Constraint>) : string =
        match lattice with
        | Lattice.And(a, b) -> 
            let ga = extractGenerators a
            let gb = extractGenerators b
            if ga <> "Arb.generate" then ga else gb
        | Lattice.Leaf (FieldBound(_, Range(lo, hi))) ->
            let minVal = 
                match lo with
                | Some (Inclusive v) -> v
                | Some (Exclusive v) -> v + 1m
                | None -> 0m // default lower bound
            let maxVal =
                match hi with
                | Some (Inclusive v) -> v
                | Some (Exclusive v) -> v - 1m
                | None -> 1000000m // default upper bound
            $"Gen.choose({int minVal}, {int maxVal})"
        | Lattice.Leaf (FieldBound(_, InSet items)) ->
            let formattedItems = items |> List.map (fun i -> $"\"{i}\"") |> String.concat "; "
            $"Gen.elements [{formattedItems}]"
        | Lattice.Leaf (FieldBound(_, Constraint.MaxLength len)) ->
            $"Arb.generate<string> |> Gen.map (fun s -> if s = null then \"\" else s.Substring(0, min s.Length {len}))"
        | _ -> "Arb.generate"

    let emitGenerators (tables: Canon.Introspect.TableDef list) : string =
        let sb = StringBuilder()
        sb.AppendLine("module CanonFlow.FsCheck.Generators") |> ignore
        sb.AppendLine("open FsCheck") |> ignore
        sb.AppendLine("open System") |> ignore
        sb.AppendLine("") |> ignore
        sb.AppendLine("// AUTO-GENERATED BY CANONFLOW") |> ignore
        sb.AppendLine("// These generators cover only admitted constraint patterns; unhandled patterns are not emitted.") |> ignore
        sb.AppendLine("") |> ignore
        
        for t in tables do
            sb.AppendLine($"module {t.Name}Generators =") |> ignore
            for c in t.Columns do
                if not c.CheckConstraints.IsEmpty then
                    let lattice = 
                        if not c.ParsedConstraints.IsEmpty then
                            c.ParsedConstraints |> List.reduce (fun a b -> Lattice.And(a, b))
                        else
                            Lattice.True
                    
                    let simplified = SemanticOptimizer.simplify lattice
                    if simplified <> Lattice.False then
                        let genCode = extractGenerators simplified
                        if genCode <> "Arb.generate" then
                            sb.AppendLine($"    let gen{c.Name} = {genCode}") |> ignore
                            sb.AppendLine($"    let arb{c.Name} = Arb.fromGen gen{c.Name}") |> ignore
            sb.AppendLine("") |> ignore
            
        string sb
