namespace Canon.Emit

open Canon.Introspect

module MigrationEmitter =

    let generateMigration (oldSchema: TableDef list) (newSchema: TableDef list) : string =
        let sb = System.Text.StringBuilder()
        sb.AppendLine("-- AUTO-GENERATED BY CANONFLOW MIGRATION ENGINE") |> ignore
        sb.AppendLine("BEGIN;") |> ignore
        sb.AppendLine() |> ignore

        let oldMap = oldSchema |> List.map (fun t -> t.Name, t) |> Map.ofList
        let newMap = newSchema |> List.map (fun t -> t.Name, t) |> Map.ofList

        // 1. Dropped Tables
        for kvp in oldMap do
            if not (newMap.ContainsKey(kvp.Key)) then
                sb.AppendLine($"DROP TABLE public.{kvp.Key} CASCADE;") |> ignore

        // 2. Created Tables
        for kvp in newMap do
            if not (oldMap.ContainsKey(kvp.Key)) then
                let t = kvp.Value
                sb.AppendLine($"CREATE TABLE public.{t.Name} (") |> ignore
                let cols = 
                    t.Columns |> List.map (fun c -> 
                        let nullability = if c.IsNullable then "" else " NOT NULL"
                        let pkey = if c.IsPrimaryKey then " PRIMARY KEY" else ""
                        $"    {c.Name} {c.DataType}{nullability}{pkey}"
                    )
                sb.AppendLine(String.concat ",\n" cols) |> ignore
                sb.AppendLine(");") |> ignore

        // 3. Altered Tables
        for kvp in newMap do
            if oldMap.ContainsKey(kvp.Key) then
                let oldT = oldMap.[kvp.Key]
                let newT = kvp.Value

                let oldCols = oldT.Columns |> List.map (fun c -> c.Name, c) |> Map.ofList
                let newCols = newT.Columns |> List.map (fun c -> c.Name, c) |> Map.ofList

                // Dropped columns
                for oldC in oldCols do
                    if not (newCols.ContainsKey(oldC.Key)) then
                        sb.AppendLine($"ALTER TABLE public.{newT.Name} DROP COLUMN {oldC.Key};") |> ignore

                // Added columns
                for newC in newCols do
                    if not (oldCols.ContainsKey(newC.Key)) then
                        let c = newC.Value
                        let nullability = if c.IsNullable then "" else " NOT NULL"
                        sb.AppendLine($"ALTER TABLE public.{newT.Name} ADD COLUMN {c.Name} {c.DataType}{nullability};") |> ignore
                    else
                        // Modified columns (simple type check)
                        let oC = oldCols.[newC.Key]
                        let nC = newC.Value
                        if oC.DataType <> nC.DataType then
                            sb.AppendLine($"ALTER TABLE public.{newT.Name} ALTER COLUMN {nC.Name} TYPE {nC.DataType} USING {nC.Name}::{nC.DataType};") |> ignore

                // Check constraints handling (Drop old, Add new)
                // In a real implementation, we would diff constraints by name.
                if oldT.TableConstraints <> newT.TableConstraints then
                    sb.AppendLine($"-- WARNING: Constraints drift detected in table {newT.Name}. Manual migration of CHECK bounds required.") |> ignore

        sb.AppendLine() |> ignore
        sb.AppendLine("COMMIT;") |> ignore
        sb.ToString()
