<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PostgresIntrospectionTests.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector"  />
    <PackageReference Include="Microsoft.NET.Test.Sdk"  />
    <PackageReference Include="xunit"  />
    <PackageReference Include="xunit.runner.visualstudio"  />
    <PackageReference Include="Testcontainers.PostgreSql"  />
    <PackageReference Include="Npgsql"  />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Canon.Introspect\Canon.Introspect.fsproj" />
    <ProjectReference Include="..\..\src\Canon.Core\Canon.Core.fsproj" />
    <ProjectReference Include="..\..\src\Canon.Emit\Canon.Emit.fsproj" />
  </ItemGroup>

</Project>
