<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Decode.fs" />
    <Compile Include="Sql.fs" />
    <Compile Include="Emit.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Canon.Core\Canon.Core.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pgsqlparser" Version="1.0.0" />
  </ItemGroup>

</Project>
