
import { toInt32, op_Subtraction, op_Addition, fromParts } from "../fable_modules/fable-library-js.5.6.0/Decimal.js";
import { join, concat } from "../fable_modules/fable-library-js.5.6.0/String.js";
import { reduce, isEmpty, map } from "../fable_modules/fable-library-js.5.6.0/List.js";
import { StringBuilder__AppendLine_Z721C83C5, StringBuilder_$ctor } from "../fable_modules/fable-library-js.5.6.0/System.Text.js";
import { equals, disposeSafe, getEnumerator } from "../fable_modules/fable-library-js.5.6.0/Util.js";
import { Lattice$1, SemanticOptimizer_simplify } from "../Canon.Core/Lattice.js";
import { toString } from "../fable_modules/fable-library-js.5.6.0/Types.js";

export function extractGenerators(lattice_mut) {
    extractGenerators:
    while (true) {
        const lattice = lattice_mut;
        let v_1, v, v_3, v_2;
        let matchResult, a, b, hi, lo, items, len;
        switch (lattice.tag) {
            case 4: {
                matchResult = 0;
                a = lattice.fields[0];
                b = lattice.fields[1];
                break;
            }
            case 2: {
                if (lattice.fields[0].tag === 12) {
                    switch (lattice.fields[0].fields[1].tag) {
                        case 0: {
                            matchResult = 1;
                            hi = lattice.fields[0].fields[1].fields[1];
                            lo = lattice.fields[0].fields[1].fields[0];
                            break;
                        }
                        case 5: {
                            matchResult = 2;
                            items = lattice.fields[0].fields[1].fields[0];
                            break;
                        }
                        case 3: {
                            matchResult = 3;
                            len = lattice.fields[0].fields[1].fields[0];
                            break;
                        }
                        default:
                            matchResult = 4;
                    }
                }
                else {
                    matchResult = 4;
                }
                break;
            }
            default:
                matchResult = 4;
        }
        switch (matchResult) {
            case 0: {
                const ga = extractGenerators(a);
                if (ga !== "Arb.generate") {
                    return ga;
                }
                else {
                    lattice_mut = b;
                    continue extractGenerators;
                }
            }
            case 1: {
                const minVal = (lo == null) ? fromParts(0, 0, 0, false, 0) : ((lo.tag === 1) ? ((v_1 = lo.fields[0], op_Addition(v_1, fromParts(1, 0, 0, false, 0)))) : ((v = lo.fields[0], v)));
                const maxVal = (hi == null) ? fromParts(1000000, 0, 0, false, 0) : ((hi.tag === 1) ? ((v_3 = hi.fields[0], op_Subtraction(v_3, fromParts(1, 0, 0, false, 0)))) : ((v_2 = hi.fields[0], v_2)));
                return `Gen.choose(${~~toInt32(minVal)}, ${~~toInt32(maxVal)})`;
            }
            case 2:
                return concat("Gen.elements [", join("; ", map((i) => concat("\"", i, "\""), items)), "]");
            case 3:
                return `Arb.generate<string> |> Gen.map (fun s -> if s = null then "" else s.Substring(0, min s.Length ${len}))`;
            default:
                return "Arb.generate";
        }
        break;
    }
}

export function emitGenerators(tables) {
    const sb = StringBuilder_$ctor();
    StringBuilder__AppendLine_Z721C83C5(sb, "module CanonFlow.FsCheck.Generators");
    StringBuilder__AppendLine_Z721C83C5(sb, "open FsCheck");
    StringBuilder__AppendLine_Z721C83C5(sb, "open System");
    StringBuilder__AppendLine_Z721C83C5(sb, "");
    StringBuilder__AppendLine_Z721C83C5(sb, "// AUTO-GENERATED BY CANONFLOW");
    StringBuilder__AppendLine_Z721C83C5(sb, "// These FsCheck Arbitraries are mathematically guaranteed to stay within the PostgreSQL CHECK bounds.");
    StringBuilder__AppendLine_Z721C83C5(sb, "");
    const enumerator = getEnumerator(tables);
    try {
        while (enumerator["System.Collections.IEnumerator.MoveNext"]()) {
            const t = enumerator["System.Collections.Generic.IEnumerator`1.get_Current"]();
            StringBuilder__AppendLine_Z721C83C5(sb, concat("module ", t.Name, "Generators ="));
            const enumerator_1 = getEnumerator(t.Columns);
            try {
                while (enumerator_1["System.Collections.IEnumerator.MoveNext"]()) {
                    const c = enumerator_1["System.Collections.Generic.IEnumerator`1.get_Current"]();
                    if (!isEmpty(c.CheckConstraints)) {
                        const simplified = SemanticOptimizer_simplify(!isEmpty(c.ParsedConstraints) ? reduce((a, b) => (new Lattice$1(4, [a, b])), c.ParsedConstraints) : (new Lattice$1(0, [])));
                        if (!equals(simplified, new Lattice$1(1, []))) {
                            const genCode = extractGenerators(simplified);
                            if (genCode !== "Arb.generate") {
                                StringBuilder__AppendLine_Z721C83C5(sb, concat("    let gen", c.Name, " = ", genCode));
                                StringBuilder__AppendLine_Z721C83C5(sb, concat("    let arb", c.Name, " = Arb.fromGen gen", c.Name));
                            }
                        }
                    }
                }
            }
            finally {
                disposeSafe(enumerator_1);
            }
            StringBuilder__AppendLine_Z721C83C5(sb, "");
        }
    }
    finally {
        disposeSafe(enumerator);
    }
    return toString(sb);
}

