namespace Canon.Cli

open System
open Argu
open Canon.Core
open Canon.Introspect.Postgres
open Canon.Fable

type CliArguments =
    | [<CliPrefix(CliPrefix.DoubleDash)>] Pg of string
    | [<CliPrefix(CliPrefix.DoubleDash)>] Contracts
    | [<CliPrefix(CliPrefix.DoubleDash)>] Demo
    | [<CliPrefix(CliPrefix.DoubleDash)>] Verify
    | [<CliPrefix(CliPrefix.DoubleDash)>] ScaffoldForms
    | [<CliPrefix(CliPrefix.DoubleDash)>] MigrateTo of string
    
    interface IArgParserTemplate with
        member s.Usage =
            match s with
            | Pg _ -> "Introspect a Postgres database using the provided connection string."
            | Contracts -> "Emit JSON Schema and TypeScript clients."
            | Demo -> "Run the 30-minute stranger demo."
            | Verify -> "Run in strict mode for CI/CD. Fails if any constraints are unsupported or approximate."
            | ScaffoldForms -> "Generate AI-assisted React Hook Form components from DB constraints."
            | MigrateTo _ -> "Compare with a target database and generate migration SQL scripts."

module Program =
    [<EntryPoint>]
    let main argv =
        let errorHandler = ProcessExiter(colorizer = function ErrorCode.HelpText -> None | _ -> Some ConsoleColor.Red)
        let parser = ArgumentParser.Create<CliArguments>(programName = "canonflow", errorHandler = errorHandler)
        
        let results = parser.ParseCommandLine(inputs = argv, raiseOnUsage = true)
        
        if results.Contains(Pg) then
            let connStr = results.GetResult(Pg)
            printfn "Starting CanonFlow Introspection on Postgres..."
            
            try
                let provider = PostgresSchemaProvider(connStr) :> Canon.Introspect.ISchemaProvider
                let tables = provider.Harvest()
                
                printfn "\n[Harvest Results]"
                for t in tables do
                    printfn $"Table: {t.Schema}.{t.Name}"
                    for c in t.Columns do
                        let constraints = String.Join(", ", c.CheckConstraints)
                        printfn $"  - {c.Name} ({c.DataType}) -> {constraints}"
                
                // Emitting the Semantic Catalog and Contracts
                if results.Contains(Contracts) then
                    printfn "\n[Emitting OKF Catalog, OpenMetadata, and TypeScript]"
                    System.IO.Directory.CreateDirectory("output/openmetadata") |> ignore
                    System.IO.Directory.CreateDirectory("client/src") |> ignore
                    
                    let tsSb = System.Text.StringBuilder()
                    tsSb.AppendLine("// AUTO-GENERATED BY CANONFLOW") |> ignore
                    
                    for t in tables do
                        let md = Canon.Contracts.Okf.OkfCatalog.emitLineage t LineageGrade.Declared
                        System.IO.File.WriteAllText($"output/catalog_{t.Name}.md", md)
                        
                        let omJson = Canon.Contracts.OpenMetadata.OpenMetadataEmitter.emitTableEntity t
                        System.IO.File.WriteAllText($"output/openmetadata/{t.Name}.json", omJson)
                        
                        for c in t.Columns do
                            if not c.CheckConstraints.IsEmpty then
                                let lattice = 
                                    c.CheckConstraints 
                                    |> List.map (fun s -> if s.StartsWith("CHECK ") then s.Substring(6) else s)
                                    |> List.map Canon.Introspect.SqlParser.parseConstraint 
                                    |> List.reduce (fun a b -> Lattice.And(a, b))
                                let tsCode, fidelity = Transpiler.emitValidator $"{t.Name}_{c.Name}" lattice
                                tsSb.AppendLine($"// Fidelity: {fidelity}") |> ignore
                                tsSb.AppendLine(tsCode) |> ignore
                    
                    System.IO.File.WriteAllText("client/src/validators.ts", tsSb.ToString())
                    printfn "Artifacts saved to 'output/' and TypeScript generated in 'client/src/validators.ts'."

                    // Generate the Mathematical Proof Report
                    let proofReport, totalApprox, totalUnsupported = Canon.Cli.ProofEmitter.emitProofReport tables
                    System.IO.File.WriteAllText("output/PROOF.md", proofReport)
                    printfn "\n[Proof Engine] Signed certification generated at 'output/PROOF.md'."
                    
                    if results.Contains(Verify) then
                        if totalUnsupported > 0 || totalApprox > 0 then
                            printfn $"\n[CI/CD CHECK FAILED] Found {totalUnsupported} unsupported and {totalApprox} approximate bounds!"
                            Environment.Exit(1)
                        else
                            printfn "\n[CI/CD CHECK PASSED] 100%% exact mathematical fidelity achieved!"
                
                // Scaffold React Forms
                if results.Contains(ScaffoldForms) then
                    printfn "\n[Scaffolding AI-Assisted React Forms]"
                    System.IO.Directory.CreateDirectory("client/src/forms") |> ignore
                    for t in tables do
                        let formCode = Canon.Cli.ReactScaffold.generateForm t
                        let fileName = $"client/src/forms/{t.Name.Substring(0, 1).ToUpper()}{t.Name.Substring(1)}Form.tsx"
                        System.IO.File.WriteAllText(fileName, formCode)
                        printfn $"Generated React Form: {fileName}"

                // Demo transpilation of a constraint
                if results.Contains(Demo) then
                    printfn "\n[Transpilation Demo]"
                    let exampleLattice = Lattice.Leaf (Range(Some(Exclusive 0m), None))
                    let tsCode, fidelity = Transpiler.emitValidator "price" exampleLattice
                    printfn "Fidelity: %A" fidelity
                    printfn "%s" tsCode
                
                // Diff and Migration Output
                if results.Contains(MigrateTo) then
                    printfn "\n[Schema Migration Engine]"
                    let newConnStr = results.GetResult(MigrateTo)
                    let newProvider = PostgresSchemaProvider(newConnStr) :> Canon.Introspect.ISchemaProvider
                    let newTables = newProvider.Harvest()
                    
                    let migrationSql = Canon.Emit.MigrationEmitter.generateMigration tables newTables
                    System.IO.Directory.CreateDirectory("output/migrations") |> ignore
                    let path = $"output/migrations/{DateTime.UtcNow:yyyyMMddHHmmss}_migration.sql"
                    System.IO.File.WriteAllText(path, migrationSql)
                    printfn $"Migration script generated: {path}"
                    printfn "\n=== MIGRATION PREVIEW ==="
                    printfn "%s" migrationSql
                
                
                0
            with
            | ex -> 
                printfn $"Error connecting or introspecting: {ex.Message}"
                1
        else
            printfn "%s" (parser.PrintUsage())
            0
