namespace Canon.Cli

open System
open Argu
open Canon.Core
open Canon.Introspect.Postgres
open Canon.Fable

type CliArguments =
    | [<CliPrefix(CliPrefix.DoubleDash)>] Pg of string
    | [<CliPrefix(CliPrefix.DoubleDash)>] Contracts
    | [<CliPrefix(CliPrefix.DoubleDash)>] Demo
    
    interface IArgParserTemplate with
        member s.Usage =
            match s with
            | Pg _ -> "Introspect a Postgres database using the provided connection string."
            | Contracts -> "Emit JSON Schema and TypeScript clients."
            | Demo -> "Run the 30-minute stranger demo."

module Program =
    [<EntryPoint>]
    let main argv =
        let errorHandler = ProcessExiter(colorizer = function ErrorCode.HelpText -> None | _ -> Some ConsoleColor.Red)
        let parser = ArgumentParser.Create<CliArguments>(programName = "canonflow", errorHandler = errorHandler)
        
        let results = parser.ParseCommandLine(inputs = argv, raiseOnUsage = true)
        
        if results.Contains(Pg) then
            let connStr = results.GetResult(Pg)
            printfn "Starting CanonFlow Introspection on Postgres..."
            
            try
                let provider = PostgresSchemaProvider(connStr) :> Canon.Introspect.ISchemaProvider
                let tables = provider.Harvest()
                
                printfn "\n[Harvest Results]"
                for t in tables do
                    printfn $"Table: {t.Schema}.{t.Name}"
                    for c in t.Columns do
                        let constraints = String.Join(", ", c.CheckConstraints)
                        printfn $"  - {c.Name} ({c.DataType}) -> {constraints}"
                
                // Emitting the Semantic Catalog and Contracts
                if results.Contains(Contracts) then
                    printfn "\n[Emitting OKF Catalog, OpenMetadata, and TypeScript]"
                    System.IO.Directory.CreateDirectory("output/openmetadata") |> ignore
                    System.IO.Directory.CreateDirectory("client/src") |> ignore
                    
                    let tsSb = System.Text.StringBuilder()
                    tsSb.AppendLine("// AUTO-GENERATED BY CANONFLOW") |> ignore
                    
                    for t in tables do
                        let md = Canon.Contracts.Okf.OkfCatalog.emitLineage t LineageGrade.Declared
                        System.IO.File.WriteAllText($"output/catalog_{t.Name}.md", md)
                        
                        let omJson = Canon.Contracts.OpenMetadata.OpenMetadataEmitter.emitTableEntity t
                        System.IO.File.WriteAllText($"output/openmetadata/{t.Name}.json", omJson)
                        
                        for c in t.Columns do
                            if not c.CheckConstraints.IsEmpty then
                                // Example AST resolution mapping directly to the TypeScript transpiler
                                let lattice = Lattice.Leaf (Range(Some(Exclusive 0m), None)) // Mock parsing for demo
                                let tsCode, fidelity = Transpiler.emitValidator $"{t.Name}_{c.Name}" lattice
                                tsSb.AppendLine($"// Fidelity: {fidelity}") |> ignore
                                tsSb.AppendLine(tsCode) |> ignore
                    
                    System.IO.File.WriteAllText("client/src/validators.ts", tsSb.ToString())
                    printfn "Artifacts saved to 'output/' and TypeScript generated in 'client/src/validators.ts'."

                    // Generate Drift Report
                    let driftViolations = 
                        [ for t in tables do
                            for c in t.Columns do
                                if not c.CheckConstraints.IsEmpty then
                                    // Mock lattice for demo
                                    let lattice = Lattice.Leaf (Range(Some(Exclusive 0m), None))
                                    let _, fidelity = Transpiler.emitValidator $"{t.Name}_{c.Name}" lattice
                                    let rawConstraint = String.Join(" AND ", c.CheckConstraints)
                                    yield! DriftEngine.analyzeFidelity c.Name "TypeScript" fidelity rawConstraint |> Option.toList ]
                    
                    if not driftViolations.IsEmpty then
                        printfn "\n[Drift Detection Report - HIGH SEVERITY]"
                        for v in driftViolations do
                            printfn $"- Field: {v.Field} ({v.TargetSystem})"
                            printfn $"  DB Truth: {v.DatabaseTruth}"
                            printfn $"  Severity: %A{v.Severity}"
                            printfn $"  Action: {v.FixAction}"
                    else
                        printfn "\n[Drift Detection Report] No drift detected! 100%% Fidelity."
                
                // Demo transpilation of a constraint
                if results.Contains(Demo) then
                    printfn "\n[Transpilation Demo]"
                    let exampleLattice = Lattice.Leaf (Range(Some(Exclusive 0m), None))
                    let tsCode, fidelity = Transpiler.emitValidator "price" exampleLattice
                    printfn "Fidelity: %A" fidelity
                    printfn "%s" tsCode
                
                0
            with
            | ex -> 
                printfn $"Error connecting or introspecting: {ex.Message}"
                1
        else
            printfn "%s" (parser.PrintUsage())
            0
