namespace Canon.Cli

open System
open System.Text
open Canon.Core
open Canon.Introspect
open Canon.Emit

/// Emits a signed markdown Proof Report for the CI pipeline.
/// Certifies that API contracts either mathematically match the DB, or
/// explicitly documents their drift/fidelity loss.
module ProofEmitter =

    let rec private formatLattice (l: Lattice<Constraint>) : string =
        match l with
        | True -> "Any"
        | False -> "None"
        | Leaf(FieldBound(f, Range(Some(Inclusive min), None))) -> sprintf "%s >= %M" f min
        | Leaf(FieldBound(f, Range(None, Some(Inclusive max)))) -> sprintf "%s <= %M" f max
        | Leaf(FieldBound(f, Range(Some(Exclusive min), None))) -> sprintf "%s > %M" f min
        | Leaf(FieldBound(f, Range(None, Some(Exclusive max)))) -> sprintf "%s < %M" f max
        | Leaf(FieldBound(f, Range(Some(Inclusive min), Some(Inclusive max)))) -> sprintf "%M <= %s <= %M" min f max
        | Leaf(FieldBound(f, InSet items)) -> sprintf "%s IN (%s)" f (items |> List.map (sprintf "'%s'") |> String.concat ", ")
        | Leaf(RelativeBound(colA, op, colB)) -> sprintf "%s %s %s" colA op colB
        | Leaf(Constraint.Opaque sql) -> sql
        | And(a, b) -> sprintf "(%s AND %s)" (formatLattice a) (formatLattice b)
        | Or(a, b) -> sprintf "(%s OR %s)" (formatLattice a) (formatLattice b)
        | Not a -> sprintf "NOT (%s)" (formatLattice a)
        | _ -> "ComplexBound"

    let emitProofReport (tables: TableDef list) : string * int * int =
        let sb = StringBuilder()
        let add (s: string) = sb.AppendLine(s) |> ignore
        
        let timestamp = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss UTC")
        
        add "# CanonFlow Mathematical Proof Report"
        add ""
        add "> **GENERATED BY:** CanonFlow Proof Engine"
        add $"> **TIMESTAMP:** {timestamp}"
        add "> **STATUS:** CERTIFIED"
        add ""
        add "## Executive Summary"
        add "This document certifies the semantic translation fidelity between the database truth and the generated frontend contracts (TypeScript / OpenAPI)."
        add ""
        
        let mutable totalExact = 0
        let mutable totalApproximate = 0
        let mutable totalUnsupported = 0
        
        add "## Detailed Field Proofs"
        
        for t in tables do
            add $"### Table: `{t.Schema}.{t.Name}`"
            add ""
            add "| Column | DB Bound (Truth) | TS Fidelity | OpenAPI Fidelity |"
            add "|--------|------------------|-------------|------------------|"
            
            for c in t.Columns do
                if not c.ParsedConstraints.IsEmpty then
                    let dbAst = c.ParsedConstraints |> List.reduce (fun a b -> And(a, b))
                    let dbStr = formatLattice (SemanticOptimizer.simplify dbAst)
                    
                    let tsCode, tsFid = Canon.Fable.Transpiler.emitValidator $"{t.Name}_{c.Name}" dbAst c.IsNullable None
                    let _, openApiFid = OpenApiTranspiler.emitSchema $"{t.Name}_{c.Name}" dbAst
                    
                    let tsFidStr = 
                        match tsFid with
                        | Fidelity.Exact -> totalExact <- totalExact + 1; "✅ Exact"
                        | Fidelity.Approximate r -> totalApproximate <- totalApproximate + 1; $"⚠️ Approx ({r})"
                        | Fidelity.Unsupported r -> totalUnsupported <- totalUnsupported + 1; $"❌ Unsupported"
                        | Fidelity.Unknown -> "❓ Unknown"
                        
                    let openApiFidStr = 
                        match openApiFid with
                        | Fidelity.Exact -> totalExact <- totalExact + 1; "✅ Exact"
                        | Fidelity.Approximate r -> totalApproximate <- totalApproximate + 1; $"⚠️ Approx ({r})"
                        | Fidelity.Unsupported r -> totalUnsupported <- totalUnsupported + 1; $"❌ Unsupported"
                        | Fidelity.Unknown -> "❓ Unknown"
                        
                    add $"| `{c.Name}` | `{dbStr}` | {tsFidStr} | {openApiFidStr} |"
            add ""
            
        add "## Metrics"
        add $"- **Exact Translations:** {totalExact}"
        add $"- **Approximate (Safe but Lossy):** {totalApproximate}"
        add $"- **Unsupported (Manual Guard Required):** {totalUnsupported}"
        add ""
        
        if totalUnsupported > 0 then
            add "### ⚠️ WARNING: Unsupported Constraints Detected"
            add "Some database constraints could not be translated into frontend validators. Your system is vulnerable to 500 errors if these bounds are breached. Backend middleware guards are strictly required."
        else
            add "### ✅ SUCCESS: Full Semantic Coverage"
            add "All database constraints are safely bounded in the API/Frontend contracts."
            
        add ""
        add "---"
        add "*Mathematical proof generated by the Lattice-Bounded Semantic Engine.*"
        
        sb.ToString(), totalApproximate, totalUnsupported
